[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-content"
description = "Django content management package for handling files, images, and documents"
readme = "README.md"
license = "MIT AND (Apache-2.0 OR BSD-2-Clause)"
requires-python = ">=3.12"
dynamic = ["version"]
authors = [
    {name = "Aapo Rista", email = "aapris@gmail.com"}
]

classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Framework :: Django :: 5.0",
    "Framework :: Django :: 5.1",
    "Framework :: Django :: 5.2",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "pillow",
    "pillow-heif",
    "pdf2image",
    "python-magic",
]

[project.optional-dependencies]
dev = [
  "ruff",
  "pre-commit",
  "django-debug-toolbar",
  "ipython",
  "django-extensions"
]

test = [
  "pytest",
  "httpx",
  "pytest-cov",
  "factory-boy",
]

[tool.ruff]
# Basic configuration
line-length = 119
target-version = "py312"
ignore-init-module-imports = true
exclude = ["content/migrations/*.py"]

select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "B",    # flake8-bugbear
    "I",    # isort
    "DJ",   # flake8-django
]

# Formatting
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

# Import sorting
[tool.ruff.isort]
combine-as-imports = true
lines-after-imports = 2
known-first-party = ["django_content"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
