[tool.setuptools]
py-modules = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "django-content"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["version"]

dependencies = [
    "Django>=5.0.0,<6.0.0",
    "exifread<3.0.0",  # 3.0.0 breaks the HEIC support
    "iptcinfo3",
    "pillow",
    "pillow-heif",
    "python-magic",
]

classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.0",
    "Framework :: Django :: 5.1",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

[tool.ruff]
line-length = 120
target-version = ['py311', 'py312']

[tool.black]
line-length = 120
target-version = ['py311', 'py312']
exclude = '''
(
  migrations         # migrations are automatically generated and should we excluded
  | management/commands/  # contains old legacy python 2 code
  |
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.tox
    | \.venv
    | venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
# force-exclude is for pre-commit
force-exclude = '''
(
   migrations                     # files in this dir are ignored
)
'''

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = ["migrations", "venv"]

[tool.autoflake]
in-place = true
remove-all-unused-imports =true
remove-unused-variables = true
exclude = ["migrations", "venv"]

[tool.uv.workspace]
members = ["temp"]
