# Generated by Django 4.0.3 on 2022-04-23 13:41

import content.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='UNPROCESSED', editable=False, max_length=40)),
                ('privacy', models.CharField(choices=[('PRIVATE', 'Private'), ('RESTRICTED', 'Group'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=40, verbose_name='Privacy')),
                ('uid', models.CharField(db_index=True, default=content.models.get_uid, editable=False, max_length=40, unique=True)),
                ('originalfilename', models.CharField(editable=False, max_length=256, null=True, verbose_name='Original file name')),
                ('filesize', models.IntegerField(editable=False, null=True)),
                ('filetime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('mimetype', models.CharField(editable=False, max_length=200, null=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/arista/Documents/workspace/mestadb-py3/services/mestadb/data/content')), upload_to=content.models.upload_split_by_1000)),
                ('preview', models.ImageField(blank=True, editable=False, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/arista/Documents/workspace/mestadb-py3/services/mestadb/var/preview')), upload_to=content.models.upload_split_by_1000)),
                ('md5', models.CharField(editable=False, max_length=32, null=True)),
                ('sha1', models.CharField(editable=False, max_length=40, null=True)),
                ('linktype', models.CharField(blank=True, max_length=500)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('point_geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Author')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Keywords')),
                ('place', models.CharField(blank=True, max_length=500, verbose_name='Place')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('opens', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNPROCESSED', 'UNPROCESSED'), ('PROCESSED', 'PROCESSED'), ('DUPLICATE', 'DUPLICATE'), ('FAILED', 'FAILED')], default='UNPROCESSED', max_length=40)),
                ('filesize', models.IntegerField(editable=False, null=True)),
                ('file', models.FileField(editable=False, storage=django.core.files.storage.FileSystemStorage(location='/Users/arista/Documents/workspace/mestadb-py3/services/mestadb/var/mail/content'), upload_to=content.models.upload_split_by_1000)),
                ('md5', models.CharField(db_index=True, editable=False, max_length=32)),
                ('sha1', models.CharField(db_index=True, editable=False, max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('content', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.content')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('bitrate', models.FloatField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('content', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.content')),
                ('width', models.IntegerField(blank=True, editable=False, null=True)),
                ('height', models.IntegerField(blank=True, editable=False, null=True)),
                ('rotate', models.IntegerField(blank=True, choices=[(0, 0), (90, 90), (180, 180), (270, 270)], default=0, null=True)),
                ('thumbnail', models.ImageField(editable=False, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/arista/Documents/workspace/mestadb-py3/services/mestadb/var/preview')), upload_to=content.models.upload_split_by_1000)),
            ],
        ),
        migrations.CreateModel(
            name='Uploadinfo',
            fields=[
                ('content', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.content')),
                ('sessionid', models.CharField(blank=True, editable=False, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('useragent', models.CharField(blank=True, editable=False, max_length=500)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('content', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.content')),
                ('width', models.IntegerField(blank=True, editable=False, null=True)),
                ('height', models.IntegerField(blank=True, editable=False, null=True)),
                ('duration', models.FloatField(blank=True, editable=False, null=True)),
                ('bitrate', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('thumbnail', models.ImageField(editable=False, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/arista/Documents/workspace/mestadb-py3/services/mestadb/var/preview')), upload_to=content.models.upload_split_by_1000)),
            ],
        ),
        migrations.CreateModel(
            name='Videoinstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimetype', models.CharField(editable=False, max_length=200)),
                ('filesize', models.IntegerField(blank=True, editable=False, null=True)),
                ('duration', models.FloatField(blank=True, editable=False, null=True)),
                ('bitrate', models.FloatField(blank=True, editable=False, null=True)),
                ('extension', models.CharField(editable=False, max_length=16)),
                ('width', models.IntegerField(blank=True, editable=False, null=True)),
                ('height', models.IntegerField(blank=True, editable=False, null=True)),
                ('framerate', models.FloatField(blank=True, editable=False, null=True)),
                ('file', models.FileField(editable=False, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/arista/Documents/workspace/mestadb-py3/services/mestadb/var/video')), upload_to=content.models.upload_split_by_1000)),
                ('command', models.CharField(editable=False, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='videoinstances', to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='contentgroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.group'),
        ),
        migrations.AddField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.content'),
        ),
        migrations.AddField(
            model_name='content',
            name='peers',
            field=models.ManyToManyField(blank=True, editable=False, to='content.content'),
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Audioinstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimetype', models.CharField(editable=False, max_length=200)),
                ('filesize', models.IntegerField(blank=True, editable=False, null=True)),
                ('duration', models.FloatField(blank=True, editable=False, null=True)),
                ('bitrate', models.FloatField(blank=True, editable=False, null=True)),
                ('extension', models.CharField(editable=False, max_length=16)),
                ('file', models.FileField(editable=False, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/arista/Documents/workspace/mestadb-py3/services/mestadb/var/audio')), upload_to=content.models.upload_split_by_1000)),
                ('command', models.CharField(editable=False, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='audioinstances', to='content.content')),
            ],
        ),
    ]
