# Generated by Django 5.1.7 on 2025-09-10 18:55

import content.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioinstance",
            name="file",
            field=models.FileField(
                editable=False,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("media/var/audio")
                ),
                upload_to=content.models.upload_split_by_1000,
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("media/data/content")
                ),
                upload_to=content.models.upload_split_by_1000,
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="preview",
            field=models.ImageField(
                blank=True,
                editable=False,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("media/var/preview")
                ),
                upload_to=content.models.upload_split_by_1000,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(
                editable=False,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("media/var/preview")
                ),
                upload_to=content.models.upload_split_by_1000,
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="file",
            field=models.FileField(
                editable=False,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("media/var/mail/content")
                ),
                upload_to=content.models.upload_split_by_1000,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                editable=False,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("media/var/preview")
                ),
                upload_to=content.models.upload_split_by_1000,
            ),
        ),
        migrations.AlterField(
            model_name="videoinstance",
            name="file",
            field=models.FileField(
                editable=False,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("media/var/video")
                ),
                upload_to=content.models.upload_split_by_1000,
            ),
        ),
    ]
