# Generated by Django 5.2.6 on 2025-09-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_audioinstance_file_alter_content_file_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mail",
        ),
        migrations.RenameField(
            model_name="audioinstance",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="audioinstance",
            old_name="filesize",
            new_name="file_size",
        ),
        migrations.RenameField(
            model_name="content",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="content",
            old_name="filesize",
            new_name="file_size",
        ),
        migrations.RenameField(
            model_name="content",
            old_name="originalfilename",
            new_name="original_filename",
        ),
        migrations.RenameField(
            model_name="content",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="videoinstance",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="videoinstance",
            old_name="filesize",
            new_name="file_size",
        ),
        migrations.RemoveField(
            model_name="content",
            name="md5",
        ),
    ]
